const providesContext = {
  'prc-chart-builder/chartData': 'chartData',
  // 'prc-chart-builder/chartType': 'chartType',
  // 'prc-chart-builder/chartOrientation': 'chartOrientation',
  // 'prc-chart-builder/chartLayoutWidth': 'width',
  // 'prc-chart-builder/chartLayoutHeight': 'height',
  // 'prc-chart-builder/chartLayoutPaddingTop': 'paddingTop',
  // 'prc-chart-builder/chartLayoutPaddingRight': 'paddingRight',
  // 'prc-chart-builder/chartLayoutPaddingBottom': 'paddingBottom',
  // 'prc-chart-builder/chartLayoutPaddingLeft': 'paddingLeft',
  // 'prc-chart-builder/colorValue': 'colorValue',
  // 'prc-chart-builder/xAxisActive': 'xAxisActive',
  // 'prc-chart-builder/xMinDomain': 'xMinDomain',
  // 'prc-chart-builder/xMaxDomain': 'xMaxDomain',
  // 'prc-chart-builder/xTickNum': 'xTickNum',
  // 'prc-chart-builder/xTickExact': 'xTickExact',
  // 'prc-chart-builder/yAxisActive': 'yAxisActive',
  // 'prc-chart-builder/yMinDomain': 'yMinDomain',
  // 'prc-chart-builder/yMaxDomain': 'yMaxDomain',
  // 'prc-chart-builder/yTickNum': 'yTickNum',
  // 'prc-chart-builder/yTickExact': 'yTickExact',
  // 'prc-chart-builder/lineInterpolation': 'lineInterpolation',
  // 'prc-chart-builder/lineNodes': 'lineNodes',
};

const usesContext = [
  'prc-chart-builder/chartData',
  // 'prc-chart-builder/chartType',
  // 'prc-chart-builder/chartOrientation',
  // 'prc-chart-builder/chartLayoutWidth',
  // 'prc-chart-builder/chartLayoutHeight',
  // 'prc-chart-builder/chartLayoutPaddingTop',
  // 'prc-chart-builder/chartLayoutPaddingRight',
  // 'prc-chart-builder/chartLayoutPaddingBottom',
  // 'prc-chart-builder/chartLayoutPaddingLeft',
  // 'prc-chart-builder/xAxisActive',
  // 'prc-chart-builder/xMinDomain',
  // 'prc-chart-builder/xMaxDomain',
  // 'prc-chart-builder/xTickNum',
  // 'prc-chart-builder/xTickExact',
  // 'prc-chart-builder/yAxisActive',
  // 'prc-chart-builder/yMinDomain',
  // 'prc-chart-builder/yMaxDomain',
  // 'prc-chart-builder/yTickNum',
  // 'prc-chart-builder/yTickExact',
  // 'prc-chart-builder/colorValue',
  // 'prc-chart-builder/lineInterpolation',
  // 'prc-chart-builder/lineNodes',
];

export { providesContext, usesContext };
